// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project1.Models;

#nullable disable

namespace Project1.Migrations
{
    [DbContext(typeof(WebTaContext))]
    partial class WebTaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeThiMauCauHoi", b =>
                {
                    b.Property<int>("MaDe")
                        .HasColumnType("int")
                        .HasColumnName("ma_de");

                    b.Property<int>("MaCau")
                        .HasColumnType("int")
                        .HasColumnName("ma_cau");

                    b.HasKey("MaDe", "MaCau")
                        .HasName("PK__DeThiMau__CFA2B1D7E2DB2083");

                    b.HasIndex("MaCau");

                    b.ToTable("DeThiMau_CauHoi", (string)null);
                });

            modelBuilder.Entity("Project1.Models.BaiHoc", b =>
                {
                    b.Property<int>("MaBai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_bai");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBai"));

                    b.Property<string>("DuongDan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("duong_dan");

                    b.Property<string>("LoaiNoiDung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loai_noi_dung");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tieu_de");

                    b.HasKey("MaBai")
                        .HasName("PK__BaiHoc__03FFDF7033CBE4A7");

                    b.ToTable("BaiHoc", (string)null);
                });

            modelBuilder.Entity("Project1.Models.CauHoi", b =>
                {
                    b.Property<int>("MaCau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_cau");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCau"));

                    b.Property<int?>("MaDoan")
                        .HasColumnType("int")
                        .HasColumnName("ma_doan");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.HasKey("MaCau")
                        .HasName("PK__CauHoi__043FED5DF5C14A3D");

                    b.HasIndex("MaDoan");

                    b.ToTable("CauHoi", (string)null);
                });

            modelBuilder.Entity("Project1.Models.DeThiMau", b =>
                {
                    b.Property<int>("MaDe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_de");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDe"));

                    b.Property<string>("Loai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loai");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tieu_de");

                    b.HasKey("MaDe")
                        .HasName("PK__DeThiMau__0FE14F02BD6445BE");

                    b.ToTable("DeThiMau", (string)null);
                });

            modelBuilder.Entity("Project1.Models.DoanVan", b =>
                {
                    b.Property<int>("MaDoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_doan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDoan"));

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tieu_de");

                    b.Property<string>("TomTat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tom_tat");

                    b.Property<string>("TuKhoa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tu_khoa");

                    b.HasKey("MaDoan")
                        .HasName("PK__DoanVan__99090DA573447039");

                    b.ToTable("DoanVan", (string)null);
                });

            modelBuilder.Entity("Project1.Models.GhiAm", b =>
                {
                    b.Property<int>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ma"));

                    b.Property<double?>("Diem")
                        .HasColumnType("float")
                        .HasColumnName("diem");

                    b.Property<string>("DuongDanAudio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("duong_dan_audio");

                    b.Property<int?>("LienKetId")
                        .HasColumnType("int")
                        .HasColumnName("lien_ket_id");

                    b.Property<string>("LoaiLienKet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loai_lien_ket");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nhan_xet");

                    b.Property<string>("VanBan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("van_ban");

                    b.HasKey("Ma")
                        .HasName("PK__GhiAm__3213C8B760ACF60F");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("GhiAm", (string)null);
                });

            modelBuilder.Entity("Project1.Models.KetBan", b =>
                {
                    b.Property<int>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ma"));

                    b.Property<int?>("MaNguoi1")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_1");

                    b.Property<int?>("MaNguoi2")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_2");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("cho")
                        .HasColumnName("trang_thai");

                    b.HasKey("Ma")
                        .HasName("PK__KetBan__3213C8B768656821");

                    b.HasIndex("MaNguoi2");

                    b.HasIndex(new[] { "MaNguoi1", "MaNguoi2" }, "UQ_KetBan")
                        .IsUnique()
                        .HasFilter("[ma_nguoi_1] IS NOT NULL AND [ma_nguoi_2] IS NOT NULL");

                    b.ToTable("KetBan", (string)null);
                });

            modelBuilder.Entity("Project1.Models.KetQuaBaiThi", b =>
                {
                    b.Property<int>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ma"));

                    b.Property<string>("ChiTiet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chi_tiet");

                    b.Property<double?>("Diem")
                        .HasColumnType("float")
                        .HasColumnName("diem");

                    b.Property<int?>("MaDe")
                        .HasColumnType("int")
                        .HasColumnName("ma_de");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("Ma")
                        .HasName("PK__KetQuaBa__3213C8B7B1A6B463");

                    b.HasIndex("MaDe");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("KetQuaBaiThi", (string)null);
                });

            modelBuilder.Entity("Project1.Models.LuaChon", b =>
                {
                    b.Property<int>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ma"));

                    b.Property<bool>("LaDapAn")
                        .HasColumnType("bit")
                        .HasColumnName("la_dap_an");

                    b.Property<int?>("MaCau")
                        .HasColumnType("int")
                        .HasColumnName("ma_cau");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.HasKey("Ma")
                        .HasName("PK__LuaChon__3213C8B701CE516C");

                    b.HasIndex("MaCau");

                    b.ToTable("LuaChon", (string)null);
                });

            modelBuilder.Entity("Project1.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mat_khau");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("NgonNguUaThich")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ngon_ngu_ua_thich");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_dang_nhap");

                    b.HasKey("MaNguoiDung")
                        .HasName("PK__NguoiDun__19C32CF7874D3E46");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__NguoiDun__363698B33605E88F")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiDun__AB6E616459BB182D")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("Project1.Models.NguoiDungBaiHoc", b =>
                {
                    b.Property<int>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ma"));

                    b.Property<double?>("Diem")
                        .HasColumnType("float")
                        .HasColumnName("diem");

                    b.Property<int?>("MaBai")
                        .HasColumnType("int")
                        .HasColumnName("ma_bai");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_hoan_thanh");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("chua_bat_dau")
                        .HasColumnName("trang_thai");

                    b.HasKey("Ma")
                        .HasName("PK__NguoiDun__3213C8B7579B0F96");

                    b.HasIndex("MaBai");

                    b.HasIndex(new[] { "MaNguoiDung", "MaBai" }, "UQ_NguoiDung_BaiHoc")
                        .IsUnique()
                        .HasFilter("[ma_nguoi_dung] IS NOT NULL AND [ma_bai] IS NOT NULL");

                    b.ToTable("NguoiDung_BaiHoc", (string)null);
                });

            modelBuilder.Entity("Project1.Models.NguoiDungTuVung", b =>
                {
                    b.Property<int>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ma"));

                    b.Property<bool?>("DaThanhThao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("da_thanh_thao");

                    b.Property<double?>("HeSoDe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(2.5)
                        .HasColumnName("he_so_de");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<int?>("MaTu")
                        .HasColumnType("int")
                        .HasColumnName("ma_tu");

                    b.Property<DateTime?>("NgayOnTapCuoi")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_on_tap_cuoi");

                    b.Property<DateTime?>("NgayOnTapTiep")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_on_tap_tiep");

                    b.HasKey("Ma")
                        .HasName("PK__NguoiDun__3213C8B73A313E59");

                    b.HasIndex("MaTu");

                    b.HasIndex(new[] { "MaNguoiDung", "MaTu" }, "UQ_NguoiDung_TuVung")
                        .IsUnique()
                        .HasFilter("[ma_nguoi_dung] IS NOT NULL AND [ma_tu] IS NOT NULL");

                    b.ToTable("NguoiDung_TuVung", (string)null);
                });

            modelBuilder.Entity("Project1.Models.NhatKyHoatDong", b =>
                {
                    b.Property<int>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ma"));

                    b.Property<string>("DuLieu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("du_lieu");

                    b.Property<string>("HanhDong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hanh_dong");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("Ma")
                        .HasName("PK__NhatKyHo__3213C8B768518CCB");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("NhatKyHoatDong", (string)null);
                });

            modelBuilder.Entity("Project1.Models.TuVung", b =>
                {
                    b.Property<int>("MaTu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_tu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTu"));

                    b.Property<string>("DuongDanAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("duong_dan_anh");

                    b.Property<string>("Nghia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nghia");

                    b.Property<string>("PhienAm")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("phien_am");

                    b.Property<string>("TrinhDo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("trinh_do");

                    b.Property<string>("Tu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tu");

                    b.Property<string>("TuLoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tu_loai");

                    b.Property<string>("ViDu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vi_du");

                    b.HasKey("MaTu")
                        .HasName("PK__TuVung__0FE0CD2E9C437D01");

                    b.ToTable("TuVung", (string)null);
                });

            modelBuilder.Entity("DeThiMauCauHoi", b =>
                {
                    b.HasOne("Project1.Models.CauHoi", null)
                        .WithMany()
                        .HasForeignKey("MaCau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DeThiMau___ma_ca__59FA5E80");

                    b.HasOne("Project1.Models.DeThiMau", null)
                        .WithMany()
                        .HasForeignKey("MaDe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DeThiMau___ma_de__59063A47");
                });

            modelBuilder.Entity("Project1.Models.CauHoi", b =>
                {
                    b.HasOne("Project1.Models.DoanVan", "MaDoanNavigation")
                        .WithMany("CauHois")
                        .HasForeignKey("MaDoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__CauHoi__ma_doan__5070F446");

                    b.Navigation("MaDoanNavigation");
                });

            modelBuilder.Entity("Project1.Models.GhiAm", b =>
                {
                    b.HasOne("Project1.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("GhiAms")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__GhiAm__ma_nguoi___628FA481");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("Project1.Models.KetBan", b =>
                {
                    b.HasOne("Project1.Models.NguoiDung", "MaNguoi1Navigation")
                        .WithMany("KetBanMaNguoi1Navigations")
                        .HasForeignKey("MaNguoi1")
                        .HasConstraintName("FK__KetBan__ma_nguoi__6754599E");

                    b.HasOne("Project1.Models.NguoiDung", "MaNguoi2Navigation")
                        .WithMany("KetBanMaNguoi2Navigations")
                        .HasForeignKey("MaNguoi2")
                        .HasConstraintName("FK__KetBan__ma_nguoi__68487DD7");

                    b.Navigation("MaNguoi1Navigation");

                    b.Navigation("MaNguoi2Navigation");
                });

            modelBuilder.Entity("Project1.Models.KetQuaBaiThi", b =>
                {
                    b.HasOne("Project1.Models.DeThiMau", "MaDeNavigation")
                        .WithMany("KetQuaBaiThis")
                        .HasForeignKey("MaDe")
                        .HasConstraintName("FK__KetQuaBai__ma_de__5DCAEF64");

                    b.HasOne("Project1.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("KetQuaBaiThis")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__KetQuaBai__ma_ng__5CD6CB2B");

                    b.Navigation("MaDeNavigation");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("Project1.Models.LuaChon", b =>
                {
                    b.HasOne("Project1.Models.CauHoi", "MaCauNavigation")
                        .WithMany("LuaChons")
                        .HasForeignKey("MaCau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__LuaChon__ma_cau__534D60F1");

                    b.Navigation("MaCauNavigation");
                });

            modelBuilder.Entity("Project1.Models.NguoiDungBaiHoc", b =>
                {
                    b.HasOne("Project1.Models.BaiHoc", "MaBaiNavigation")
                        .WithMany("NguoiDungBaiHocs")
                        .HasForeignKey("MaBai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__NguoiDung__ma_ba__48CFD27E");

                    b.HasOne("Project1.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("NguoiDungBaiHocs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__NguoiDung__ma_ng__47DBAE45");

                    b.Navigation("MaBaiNavigation");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("Project1.Models.NguoiDungTuVung", b =>
                {
                    b.HasOne("Project1.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("NguoiDungTuVungs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__NguoiDung__ma_ng__3F466844");

                    b.HasOne("Project1.Models.TuVung", "MaTuNavigation")
                        .WithMany("NguoiDungTuVungs")
                        .HasForeignKey("MaTu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__NguoiDung__ma_tu__403A8C7D");

                    b.Navigation("MaNguoiDungNavigation");

                    b.Navigation("MaTuNavigation");
                });

            modelBuilder.Entity("Project1.Models.NhatKyHoatDong", b =>
                {
                    b.HasOne("Project1.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("NhatKyHoatDongs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__NhatKyHoa__ma_ng__6E01572D");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("Project1.Models.BaiHoc", b =>
                {
                    b.Navigation("NguoiDungBaiHocs");
                });

            modelBuilder.Entity("Project1.Models.CauHoi", b =>
                {
                    b.Navigation("LuaChons");
                });

            modelBuilder.Entity("Project1.Models.DeThiMau", b =>
                {
                    b.Navigation("KetQuaBaiThis");
                });

            modelBuilder.Entity("Project1.Models.DoanVan", b =>
                {
                    b.Navigation("CauHois");
                });

            modelBuilder.Entity("Project1.Models.NguoiDung", b =>
                {
                    b.Navigation("GhiAms");

                    b.Navigation("KetBanMaNguoi1Navigations");

                    b.Navigation("KetBanMaNguoi2Navigations");

                    b.Navigation("KetQuaBaiThis");

                    b.Navigation("NguoiDungBaiHocs");

                    b.Navigation("NguoiDungTuVungs");

                    b.Navigation("NhatKyHoatDongs");
                });

            modelBuilder.Entity("Project1.Models.TuVung", b =>
                {
                    b.Navigation("NguoiDungTuVungs");
                });
#pragma warning restore 612, 618
        }
    }
}
